#!/usr/bin/env python
import os
import subprocess
import argparse
import json

default_ssh_key = os.environ.get("AWS_EC2_DEFAULT_SSH_KEY")
parser = argparse.ArgumentParser(description='Copy file from instance')
parser.add_argument("instance_id", help="Instance Id")
parser.add_argument("source", help="Where to copy the file from on the instance")
parser.add_argument("destination", help="Where to copy the file to")
parser.add_argument('-s', '--ssh-key', required=False if default_ssh_key else True)
args = parser.parse_args()
ssh_key = args.ssh_key if args.ssh_key else default_ssh_key

instance_ids = args.instance_id.split(",")
destination = args.destination
source = args.source

for instance_id in instance_ids:
    subprocess_args = ["aws", "ec2", "describe-instances", "--instance-ids", instance_id]

    result = subprocess.check_output(subprocess_args)

    parsed_result = json.loads(result)
    reservation = parsed_result.get("Reservations", [{}])[0]
    instance = reservation.get("Instances", [{}])[0]
    dns_name = instance.get("PublicDnsName")

    if ssh_key:
        subprocess.call(["scp", "-i", ssh_key, "ubuntu@{}:{}".format(dns_name, source), destination])

