#!/usr/bin/env python
import os
import subprocess
import argparse
import json

default_ssh_key = os.environ.get("AWS_EC2_DEFAULT_SSH_KEY")
parser = argparse.ArgumentParser(description='Shell Into an instance')
parser.add_argument('-i', '--instance-id', help='Instance ID', required=True)
parser.add_argument('-s', '--ssh-key', required=False if default_ssh_key else True)
parser.add_argument('-d', '--debug')
args = parser.parse_args()
ssh_key = args.ssh_key if args.ssh_key else default_ssh_key
instance_id = args.instance_id

subprocess_args = ["aws", "ec2", "describe-instances", "--instance-ids", instance_id]

result = subprocess.check_output(subprocess_args)

parsed_result = json.loads(result)
reservation = parsed_result.get("Reservations", [{}])[0]
instance = reservation.get("Instances", [{}])[0]
dns_name = instance.get("PublicDnsName")

if ssh_key:
    subprocess.call(["ssh", "ubuntu@{}".format(dns_name), "-i", ssh_key])

if args.debug:
    print "calling ", " ".join(subprocess_args)
    print "Default sshkey {}".format(default_ssh_key)
    print result
